version: '3'

services:
  gildedroseapi:
    build: ./gildedroseapi
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./gildedroseapi:/code
    ports:
      - "8000:8000"
  gildedroseweb:
    build: ./gildedroseweb
    command: "npm start -- --host=0.0.0.0"
    ports:
      - 4200:4200
    volumes:
      - ./gildedroseweb:/home/app/gildedroseweb
      - /home/app/gildedroseweb/node_modules
    depends_on:
      - gildedroseapi