// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GR.Repositories.EF.Entities
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    internal partial class InventoryItemType
    {
        public short InventoryItemTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte QualityDeltaStrategyId { get; set; }
        public double BaseDelta { get; set; }
        public double MinQuality { get; set; }
        public double MaxQuality { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime? ModifiedDate { get; set; }

        public System.Collections.Generic.ICollection<InventoryItem> InventoryItems { get; set; } = new System.Collections.Generic.List<InventoryItem>();


        public QualityDeltaStrategy QualityDeltaStrategy { get; set; }
    }

}
// </auto-generated>
