// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GR.Repositories.EF.Entities
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    internal partial class InventoryItem
    {
        public int InventoryItemId { get; set; }
        public short InventoryItemTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double InitialQuality { get; set; }
        public double CurrentQuality { get; set; }
        public System.DateTime InventoryDate { get; set; }
        public System.DateTime? SellByDate { get; set; }
        public System.DateTime? SaleDate { get; set; }
        public System.DateTime? DiscardDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime? ModifiedDate { get; set; }


        public InventoryItemType InventoryItemType { get; set; }
    }

}
// </auto-generated>
