// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GR.Repositories.EF.Entities
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class QualityDeltaStrategy_EntityConfig : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<QualityDeltaStrategy>
    {
        public QualityDeltaStrategy_EntityConfig()
            : this("dbo")
        {
        }

        public QualityDeltaStrategy_EntityConfig(string schema)
        {
            ToTable("QualityDeltaStrategy", schema);
            HasKey(x => x.QualityDeltaStrategyId);

            Property(x => x.QualityDeltaStrategyId).HasColumnName(@"QualityDeltaStrategyId").HasColumnType("tinyint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(1000);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
