export const LOAD_ALL_ITEMS_SUCCESS = "LOAD_ALL_ITEMS_SUCCESS";
export const LOAD_TRASH_ITEMS_SUCCESS = "LOAD_TRASH_ITEMS_SUCCESS";
export const LOAD_ITEM_SUCCESS = "LOAD_ITEM_SUCCESS";
export const PROCESS_END_OF_DAY_SUCCESS = "PROCESS_END_OF_DAY_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const END_API_CALL = "END_API_CALL";