export const LOAD_ALL_ITEMS_SUCCESS = "LOAD_ALL_ITEMS_SUCCESS";
export const LOAD_TRASH_ITEMS_SUCCESS = "LOAD_TRASH_ITEMS_SUCCESS";
export const LOAD_ITEM_SUCCESS = "LOAD_ITEM_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";