// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GildedRose.Models
{

    // AgingThreshold
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class AgingThresholdMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AgingThreshold>
    {
        public AgingThresholdMap()
            : this("dbo")
        {
        }

        public AgingThresholdMap(string schema)
        {
            ToTable("AgingThreshold", schema);
            HasKey(x => x.AgingThresholdId);

            Property(x => x.AgingThresholdId).HasColumnName(@"AgingThresholdId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.AgingSchemeId).HasColumnName(@"AgingSchemeId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.ThresholdName).HasColumnName(@"ThresholdName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(256);
            Property(x => x.DaysPrior).HasColumnName(@"DaysPrior").HasColumnType("int").IsRequired();
            Property(x => x.IncrementRate).HasColumnName(@"IncrementRate").HasColumnType("decimal").IsRequired().HasPrecision(8,2);
            Property(x => x.LastUpdated).HasColumnName(@"LastUpdated").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.AgingScheme).WithMany(b => b.AgingThresholds).HasForeignKey(c => c.AgingSchemeId).WillCascadeOnDelete(false); // FK_AgingThreshold_AgingScheme
        }
    }

}
// </auto-generated>
