// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GildedRose.Models
{

    // Category
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Category
    {
        public System.Guid CategoryId { get; set; } // CategoryId (Primary key)
        public System.Guid? AgingSchemeId { get; set; } // AgingSchemeId
        public string CategoryName { get; set; } // CategoryName (length: 256)
        public System.DateTime LastUpdated { get; set; } // LastUpdated

        // Reverse navigation

        /// <summary>
        /// Child Products where [Product].[CategoryId] point to this entity (FK_Product_Category)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Product> Products { get; set; } // Product.FK_Product_Category

        // Foreign keys

        /// <summary>
        /// Parent AgingScheme pointed by [Category].([AgingSchemeId]) (FK_Category_AgingScheme)
        /// </summary>
        public virtual AgingScheme AgingScheme { get; set; } // FK_Category_AgingScheme

        public Category()
        {
            CategoryId = System.Guid.NewGuid();
            LastUpdated = System.DateTime.UtcNow;
            Products = new System.Collections.Generic.List<Product>();
        }
    }

}
// </auto-generated>
