// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GildedRose.Models
{

    public interface IGildedRoseContext : System.IDisposable
    {
        System.Data.Entity.DbSet<AgingScheme> AgingSchemes { get; set; } // AgingScheme
        System.Data.Entity.DbSet<AgingThreshold> AgingThresholds { get; set; } // AgingThreshold
        System.Data.Entity.DbSet<Category> Categories { get; set; } // Category
        System.Data.Entity.DbSet<InventoryCsvImport> InventoryCsvImports { get; set; } // InventoryCsvImport
        System.Data.Entity.DbSet<Product> Products { get; set; } // Product
        System.Data.Entity.DbSet<VProductCategoryAging> VProductCategoryAgings { get; set; } // vProductCategoryAging

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        // Stored Procedures
        int ImportAgingCsv(System.DateTime? receiptDate);
        // ImportAgingCsvAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<ProductAgingList> ProductAgingList(System.DateTime? referenceDate, System.DateTime? asOfDate, System.Guid? productId);
        System.Collections.Generic.List<ProductAgingList> ProductAgingList(System.DateTime? referenceDate, System.DateTime? asOfDate, System.Guid? productId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProductAgingList>> ProductAgingListAsync(System.DateTime? referenceDate, System.DateTime? asOfDate, System.Guid? productId);

    }

}
// </auto-generated>
