// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GildedRose.Models
{

    // InventoryCsvImport
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class InventoryCsvImport
    {
        public string ProductName { get; set; } // ProductName (Primary key) (length: 150)
        public string ProductCategory { get; set; } // ProductCategory (Primary key) (length: 150)
        public int SellInDays { get; set; } // SellInDays (Primary key)
        public int Quality { get; set; } // Quality (Primary key)
    }

}
// </auto-generated>
