// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GildedRose.Models
{

    // Product
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Product
    {
        public System.Guid ProductId { get; set; } // ProductId (Primary key)
        public System.Guid CategoryId { get; set; } // CategoryId
        public string ProductName { get; set; } // ProductName (length: 256)
        public int? SellIn { get; set; } // SellIn
        public int? InitialQuality { get; set; } // InitialQuality
        public System.DateTime? ReceiptDate { get; set; } // ReceiptDate
        public System.DateTime LastUpdated { get; set; } // LastUpdated

        // Reverse navigation

        /// <summary>
        /// Child AgingSchemes where [AgingScheme].[ProductId] point to this entity (FK_AgingScheme_Product)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AgingScheme> AgingSchemes { get; set; } // AgingScheme.FK_AgingScheme_Product

        // Foreign keys

        /// <summary>
        /// Parent Category pointed by [Product].([CategoryId]) (FK_Product_Category)
        /// </summary>
        public virtual Category Category { get; set; } // FK_Product_Category

        public Product()
        {
            ProductId = System.Guid.NewGuid();
            AgingSchemes = new System.Collections.Generic.List<AgingScheme>();
        }
    }

}
// </auto-generated>
