// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GildedRose.Models
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class ProductAgingList
    {
        public System.Guid ProductId { get; set; }
        public System.String ProductName { get; set; }
        public System.String CategoryName { get; set; }
        public System.String SchemeName { get; set; }
        public System.DateTime? ReceiptDate { get; set; }
        public System.Int32? SellIn { get; set; }
        public System.Int32? InitialQuality { get; set; }
        public System.Int32? RemainingQuality { get; set; }
        public System.Int32? RemainingDays { get; set; }
    }

}
// </auto-generated>
