// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GildedRose.Models
{

    // vProductCategoryAging
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class VProductCategoryAging
    {
        public System.Guid ProductId { get; set; } // ProductId (Primary key)
        public string ProductName { get; set; } // ProductName (Primary key) (length: 256)
        public int? SellIn { get; set; } // SellIn
        public int? InitialQuality { get; set; } // InitialQuality
        public string CategoryName { get; set; } // CategoryName (Primary key) (length: 256)
        public System.Guid? AgingSchemeId { get; set; } // AgingSchemeId
        public string SchemeName { get; set; } // SchemeName (length: 256)
        public decimal? DefaultIncrement { get; set; } // DefaultIncrement
        public decimal? MaxQuality { get; set; } // MaxQuality
        public bool? ScrapOnExpiration { get; set; } // ScrapOnExpiration
    }

}
// </auto-generated>
