// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GildedRose.Models
{

    // vProductCategoryAging
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class VProductCategoryAgingMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<VProductCategoryAging>
    {
        public VProductCategoryAgingMap()
            : this("dbo")
        {
        }

        public VProductCategoryAgingMap(string schema)
        {
            ToTable("vProductCategoryAging", schema);
            HasKey(x => new { x.ProductId, x.ProductName, x.CategoryName });

            Property(x => x.ProductId).HasColumnName(@"ProductId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ProductName).HasColumnName(@"ProductName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(256).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SellIn).HasColumnName(@"SellIn").HasColumnType("int").IsOptional();
            Property(x => x.InitialQuality).HasColumnName(@"InitialQuality").HasColumnType("int").IsOptional();
            Property(x => x.CategoryName).HasColumnName(@"CategoryName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(256).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.AgingSchemeId).HasColumnName(@"AgingSchemeId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.SchemeName).HasColumnName(@"SchemeName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(256);
            Property(x => x.DefaultIncrement).HasColumnName(@"DefaultIncrement").HasColumnType("decimal").IsOptional().HasPrecision(8,2);
            Property(x => x.MaxQuality).HasColumnName(@"MaxQuality").HasColumnType("decimal").IsOptional().HasPrecision(8,2);
            Property(x => x.ScrapOnExpiration).HasColumnName(@"ScrapOnExpiration").HasColumnType("bit").IsOptional();
        }
    }

}
// </auto-generated>
